trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Use a specific version of Python (3.10.12)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.12'
    addToPath: true

# Install system dependencies and pip
- script: |
    sudo apt-get update
    sudo apt-get -y install cmake make gcc g++ libssl-dev python3-dev python3-pip
    python3 -m pip install --upgrade pip
    pip3 --version
  displayName: 'Install system dependencies and pip'

# Install pip, PyYAML, and other required libraries
- script: |
    pip install pyyaml packaging
  displayName: 'Install pip, PyYAML, and packaging'

# Install Ansible and the Azure collection dependencies
- script: |
    pip3 install ansible==8.7.0
    ansible-galaxy collection install azure.azcollection
    pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
    # Find and install additional requirements.txt files
    find . -regex '.*requirements.txt$' -exec pip3 install -r {} \;
    ansible-galaxy collection install azure.azcollection --force
    # List the installed Ansible version
    ansible --version
  displayName: 'Install Ansible Azure Collection and dependencies'
