---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible_RG
        location: 'SoutheastAsia'
      register: rg_result
      until: rg_result is succeeded

    - name: Debug output
      debug:
        msg: "{{ rg_result }}"