---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"
      register: rg_result
      until: rg_result is succeeded
      retries: 5
      delay: 10

    - name: Debug output
      debug:
        msg: "{{ rg_result }}"